- name: Build with cmake & mingw
  shell: msys2 {0}
  run: |
    git clone https://github.com/jmacd/xdelta.git
    cd xdelta
    mkdir build
    cd build
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
    mingw32-make
