name: Build & Release xdelta3 for Windows

on:
  push:
    tags:
      - 'v*'  # Только при пуше тега v1.0.0, v3.1.0 и т.д.
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@f4f3dcd5162fdcbd1219777084a7f10f27f93c83  # v3.5.3

    - name: Install MSYS2
      uses: msys2/setup-msys2@4392b50dfb332105ab3eb1ec3f46f5bdb61b93ab  # v2.22.0
      with:
        update: true
        install: >-
          git
          make
          automake
          autoconf
          gcc
          mingw-w64-x86_64-toolchain

    - name: Build xdelta3
      shell: msys2 {0}
      run: |
        ./configure
        make

    - name: Rename executable
      shell: bash
      run: |
        mkdir -p dist
        cp ./xdelta3/xdelta3.exe dist/xdelta3.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: xdelta3-windows
        path: dist/xdelta3.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/xdelta3.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
